name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3

      - name: Install Ninja
        run: |
          choco install ninja -y

      - name: Install Perl
        run: |
          choco install strawberryperl -y

      - name: Install NASM
        run: |
          choco install nasm -y

      - name: Set up Clang
        run: |
          choco install llvm -y
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

      - name: Compile web directory
        run: |
          cd web
          npm install
          npm run build

      - name: Run build.bat script
        run: |
          cd backEnd
          ./build.bat

      - name: Compress build artifacts
        run: |
          powershell Compress-Archive -Path backEnd/bin/toolbox.exe -DestinationPath backEnd/bin/toolbox.zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toolbox.zip
          path: backEnd/bin/toolbox.zip
