name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js dependencies
        run: |
          cd web
          npm install

      - name: Set up Clang
        run: |
          choco install llvm -y
          refreshenv

      - name: Compile web directory
        run: |
          cd web
          npm run build

      - name: Run build.bat script
        run: |
          cd backEnd
          build.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            backEnd/bin/toolbox.exe
